### ISSUE TITLE
*^ index out of bounds exception

### ISSUE THREAD

**Issue by kevinkilroy** [BIDData/BIDMat#65]
I'm seeing this error also, using BIDMach 1.0.3 on OSX

```
import BIDMat.{CMat, CSMat, DMat, Dict, FMat, FND, GMat, GDMat, GIMat, GLMat, GSMat, GSDMat, HMat, IDict, Image, IMat, LMat, Mat, SMat, SBMat, SDMat}
import BIDMat.MatFunctions._
import BIDMat.SciFunctions._
import BIDMat.Solvers._
import BIDMat.Plotting._
import BIDMach.Learner
import BIDMach.models.{FM, GLM, KMeans, KMeansw, LDA, LDAgibbs, Model, NMF, SFA, RandomForest}
import BIDMach.networks.DNN
import BIDMach.datasources.{DataSource, MatDS, FilesDS, SFilesDS}
import BIDMach.mixins.{CosineSim, Perplexity, Top, L1Regularizer, L2Regularizer}
import BIDMach.updaters.{ADAGrad, Batch, BatchNorm, IncMult, IncNorm, Telescoping}
import BIDMach.causal.IPTW
Cant find native CPU libraries
Cant find native HDF5 library
Couldnt load CUDA runtime

Welcome to Scala version 2.11.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_77).
Type in expressions to have them evaluated.
Type :help for more information.

scala> val a = rand(3,4)
a: BIDMat.FMat =
   0.35220   0.65258  0.036466   0.99557
   0.60489   0.86963   0.97922   0.78230
   0.94532  0.058336   0.25055   0.32130

scala> val b = rand(3,4)
b: BIDMat.FMat =
  0.64503  0.13270  0.90378  0.11487
  0.82805  0.30121  0.28766  0.99566
  0.80126  0.16047  0.98435  0.80532

scala> a *^ b
java.lang.ArrayIndexOutOfBoundsException: 9
  at BIDMat.FMat.fDMultTHelper(FMat.scala:694)
  at BIDMat.FMat.multT(FMat.scala:720)
  at BIDMat.FMat.$times$up(FMat.scala:1044)
  ... 33 elided

scala>
```

**Comment by DanielTakeshi** [comment]
It says `Cant find native CPU libraries` which doesn't look good. When you got the data, did you run the command `./getdevlibs.sh` to get the libraries, before compiling (with `./sbt package`)?

**Comment by jcanny** [comment]
Well, there is a config problem so the system fell back on pure java code, which did have a bug. Fixed now.
